### ISSUE TITLE
Kernel 6.7 support

### ISSUE THREAD

**Issue by curiousercreative** [pop-os/zfs-linux#20]
OpenZFS has just published a new release with support.

**Comment by curiousercreative** [comment]
It appears Pop! is shipping kernel 6.8 while still shipping OpenZFS 2.2.2 (compatibility up to kernel 6.6). OpenZFS has published 2.2.3 with compatibility with kernel 6.7.

**Comment by jackpot51** [comment]
@mmstick it would be good to pull in upstream updates
