### ISSUE TITLE
Kernel 6.9

### ISSUE THREAD

**Issue by curiousercreative** [pop-os/zfs-linux#24]
Upstream released support just now: https://github.com/openzfs/zfs/releases/tag/zfs-2.2.5

**Comment by madeofstars0** [comment]
I've been waiting for a release as well. Is there any idea of timeline? Or is there a wiki/guide/blog/whatever that I could use to build the package locally from the PR?

**Comment by leviport** [comment]
2.2.4, released in June, supports 6.9.3, which is the current release: https://github.com/pop-os/zfs-linux/pull/23

**Comment by madeofstars0** [comment]
> 2.2.4, released in June, supports 6.9.3, which is the current release: #23

Thanks for bringing this to my attention. When 6.9.3  first came out, the zfs stuff wouldn't work and would lockup the system on boot, when it tried to drop down into the rescue shell. Trying the build now with dkms for both nvidia and zfs is now working.

Thank you.
