### ISSUE TITLE
ZFS on Root Unsupported on Noble with System76 PPA due to zfs-linux version

### ISSUE THREAD

**Issue by surfrock66** [pop-os/zfs-linux#25]
While zfs on root is supported in Ubuntu 24.04 natively, it provides version 2.2.2 which is specifically patched to support kernel version 6.8.

The System76 PPA brings with it an update to kernel 6.9.3 in the Noble repo, which forces incompatibility with the zfs dkms modules, making my system unbootable unless I select an older kernel.

System76 provides a newer zfs on linux implementation (2.2.4) however this is only in the Jammy repo, not Noble:

https://launchpad.net/~system76-dev/+archive/ubuntu/stable/+packages?field.name_filter=zfs&field.status_filter=published&field.series_filter=

Additionally, 2.2.5 is out to natively support the 6.9 kernel series.

This is quite frustrating; I love my thelio, but using the System76 drivers PPA has made my system unbootable without intervention.  I now must choose to pin my kernel version to an older version, manually select a linux kernel each boot, stop using the repo, or redo my storage from what was previously a supported configuration from the OS.

Please consider updating the support for zfs on the provided kernel version.  I wish I had discovered this before converting my system to ZFS on root (when I rebuilt for 24.04).

Additional details: https://ubuntuforums.org/showthread.php?t=2499961&p=14201580#post14201580

**Comment by leviport** [comment]
2.2.4 should be available on Noble now.
