### ISSUE TITLE
Pop!OS seems to be shipping a known extremely buggy OpenZFS patch

### ISSUE THREAD

**Issue by rincebrain** [pop-os/zfs-linux#8]
**Distribution (run `cat /etc/os-release`):**
At least 20.04 and 22.04. 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
zfs-linux 2.1.4-1pop1~1650059719~22.04~9934f01

**Issue/Bug Description:**
Pop is shipping Ubuntu's patch 4701-enable-ARC-FILL-LOCKED-flag.patch, as far as I can tell from someone reporting the bug from it against upstream OpenZFS again.

This patch is...very, very bad:
https://github.com/openzfs/zfs/issues/10971
https://bugs.launchpad.net/ubuntu/+source/zfs-linux/+bug/1906476

If you saw any reports of upgrading to Ubuntu 22.04 eating people's data on ZFS, this was the patch why.

I would strongly encourage you to drop it.

**Steps to reproduce (if you know):**

> Install Pop!OS ZFS package
> Try to use ZFS
> Suddenly your data is gone.

**Expected behavior:**

Retaining your data intact.

**Other Notes:**

Sorry if this is the incorrect repo, I'm not very familiar with Pop!OS, but this seemed important to report.

**Comment by mmstick** [comment]
I will remove the patch. The patch is still in the latest version of https://salsa.debian.org/zfsonlinux-team/zfs.git so it might be good for Debian/Ubuntu to know to remove it.

**Comment by rincebrain** [comment]
The patch is there, but it's not actually applied in the series file - Debian themselves never shipped it, they just kept it there because they keep the ubuntu/ patch folder, AFAIK.

**Comment by deepio** [comment]
When will this patch be available in Pop? After updating/upgrading I don't seem to have it yet
